In [11]:
import pandas as pd
from dotenv import load_dotenv
from supabase import Client, create_client
import os

In [2]:
data = pd.read_csv(
    "./data/global_wordfreq.release_UTF-8.txt", sep="\t", header=None
).rename(
    columns={0:"char", 1:"freq"}
)

In [3]:
data

           char        freq
0             第  2002074595
1             的   943370349
2             了   255733044
3             在   197672850
4             是   171296602
...         ...         ...
1048571    赤崖堡村          25
1048572      经军          25
1048573     于松如          25
1048574  11．86％          25
1048575     胡良成          25

[1048576 rows x 2 columns]

In [6]:
# Calculate relative frequency as percentage
total_instances = sum(data.freq)
data["rel_freq_pct"] = data.freq / total_instances * 100
data.head()

  char        freq  rel_freq_pct
0    第  2002074595     10.632977
1    的   943370349      5.010220
2    了   255733044      1.358193
3    在   197672850      1.049836
4    是   171296602      0.909753

In [12]:
# Grab data from our database and compare
def get_all_vocabulary(client: Client):
    range_start = 0
    all_data = []

    while True:
        response = client.table("vocabulary").select("*").range(range_start, range_start + 999).execute()
        data = response.data
        all_data += data

        if len(data) < 1000:
            break

        range_start += 1000
    
    return all_data

load_dotenv()
client = create_client(
    os.environ["DB_URL"],
    os.environ["DB_SERVICE_KEY"]
)

vocabulary_data = get_all_vocabulary(client)

In [17]:
# Get frequency of matches with both traditional and simplified
trad_char_set = set([entry["traditional"] for entry in vocabulary_data])
simp_char_set = set([entry["simplified"] for entry in vocabulary_data])

# Get set of characters in dataframe
df_char_set = set(data.char)

In [23]:
trad_char_intersect = len(trad_char_set.intersection(df_char_set))
simp_char_intersect = len(simp_char_set.intersection(df_char_set))

print(f"Traditional overlap: {trad_char_intersect}")
print(f"Simplified overlap: {simp_char_intersect}")

Traditional overlap: 3594
Simplified overlap: 6937

In [39]:
# Update original data and upsert back into table
df_filtered = data[data["char"].isin(simp_char_set)]

# Convert to dict for quick look-up
freq_lookup = dict()
for k, v in df_filtered.iterrows():
    char = v["char"]
    freq = v["rel_freq_pct"]
    freq_lookup[char] = freq

freq_lookup

{'第': 10.632976602799742,
 '的': 5.010220335317738,
 '了': 1.358192886621568,
 '在': 1.049836401854319,
 '是': 0.9097526964049505,
 '我': 0.8996332521664626,
 '和': 0.6313608945721991,
 '有': 0.5006743667401303,
 '你': 0.4699563638888518,
 '个': 0.4666213557215754,
 '也': 0.41032226722145654,
 '这': 0.389044561827894,
 '不': 0.37258318168617266,
 '他': 0.3561069201806323,
 '上': 0.353232830657324,
 '人': 0.34790258849971945,
 '中': 0.34765722656999937,
 '就': 0.3452811847464976,
 '年': 0.31775765624093405,
 '为': 0.3049529490348917,
 '对': 0.3003197888349387,
 '说': 0.2813054209745126,
 '都': 0.2789724405706556,
 '要': 0.26954830973373384,
 '到': 0.2689775706611254,
 '着': 0.23975779505229883,
 '与': 0.2310161250471922,
 '将': 0.2286769414195877,
 '日': 0.22444658181782437,
 '我们': 0.2219331077846348,
 '好': 0.22055609833226347,
 '月': 0.21765124761722077,
 '会': 0.2125818382718505,
 '大': 0.20373964205176648,
 '来': 0.20165805685004165,
 '还': 0.1985494875934677,
 '等': 0.19259412193587888,
 '而': 0.1900681511685472,
 '地': 0.18920266868128313,
 '自己': 0.1814109310442709,
 '后': 0.179338868428316,
 '两': 0.17391075023437275,
 '被': 0.16163771984865863,
 '没有': 0.16148363240808702,
 '去': 0.1596445996280664,
 '但': 0.1572807358799526,
 '从': 0.15458662482099106,
 '很': 0.15426393503359606,
 '给': 0.15376544121153377,
 '时': 0.14909690988986965,
 '以': 0.1485146513032985,
 '中国': 0.1477051996469733,
 '元': 0.146459121765705,
 '看': 0.14486025146673254,
 '啊': 0.1428945040331222,
 '下': 0.14200253038142938,
 '她': 0.14174721036564195,
 '又': 0.14163923284679653,
 '可以': 0.13745563641720546,
 '把': 0.13549000582513832,
 '能': 0.1269848868351994,
 '做': 0.12477966203686242,
 '出': 0.12387458088841533,
 '得': 0.11907722645440484,
 '让': 0.1166887516285118,
 '想': 0.1165491897161504,
 '那': 0.11582281770801267,
 '新': 0.11565586176475241,
 '发展': 0.11297051913250937,
 '过': 0.11290049387128383,
 '就是': 0.11210448430340474,
 '之': 0.10994936328317936,
 '小': 0.10980419297674485,
 '用': 0.10894306018147497,
 '天': 0.10865151928729859,
 '工作': 0.10462218556059394,
 '进行': 0.10441221068552275,
 '记者': 0.10438192748191957,
 '里': 0.10301753160523353,
 '最': 0.10131761992629776,
 '并': 0.10123683993211946,
 '前': 0.09873497569953962,
 '公司': 0.09805911641491469,
 '已经': 0.09800437084095084,
 '问题': 0.0973336578952055,
 '企业': 0.09610071937656686,
 '家': 0.09544572692935983,
 '吧': 0.09460219471927778,
 '没': 0.09354523549762121,
 '次': 0.09303867429809955,
 '可': 0.09224969646672883,
 '其': 0.08819711127292931,
 '现在': 0.08691884885749136,
 '向': 0.0856927243252124,
 '于': 0.08514832770961407,
 '真': 0.08508223788400233,
 '这样': 0.08479942292871058,
 '已': 0.08369038424466663,
 '该': 0.08307053454706365,
 '市场': 0.0826519603405434,
 '本': 0.08256893380214833,
 '名': 0.0824235404345859,
 '太': 0.08206050313793563,
 '再': 0.08178677526811652,
 '所': 0.08011123567289435,
 '因为': 0.07998819090595666,
 '种': 0.07962965200871922,
 '时间': 0.07852516483388043,
 '还是': 0.07761875594062437,
 '位': 0.07713409721947162,
 '比': 0.07682305440954097,
 '内': 0.07640562206355646,
 '如果': 0.07625937362833704,
 '及': 0.07555334798165209,
 '更': 0.07532326042821451,
 '道': 0.0731688139023521,
 '爱': 0.07314629535039181,
 '却': 0.07242475633335875,
 '国家': 0.07194775073328497,
 '经济': 0.07096684473428672,
 '高': 0.070582478545025,
 '手': 0.07045813789915374,
 '开始': 0.07034191242955495,
 '或': 0.0700969541342568,
 '吃': 0.0689763003386239,
 '时候': 0.06844977516815443,
 '由': 0.06824514844917383,
 '呢': 0.06713632220429931,
 '只': 0.06646102588347337,
 '目前': 0.06638539222817469,
 '今天': 0.06574306646644532,
 '它': 0.06466800742755274,
 '活动': 0.06456762991999393,
 '分': 0.0628085911092247,
 '使': 0.06174627310951909,
 '管理': 0.061521873614843174,
 '一些': 0.061517805404748466,
 '起': 0.061011902766652054,
 '通过': 0.060488011841883606,
 '这些': 0.06043035054031926,
 '才': 0.059295840399859856,
 '市': 0.059231508508375205,
 '美国': 0.059183412280414745,
 '大家': 0.05911061468802805,
 '但是': 0.05894763135723626,
 '吗': 0.0582911412138847,
 '走': 0.05802503991024838,
 '可能': 0.05802237910965117,
 '社会': 0.057943686330312605,
 '表示': 0.0572518038213329,
 '据': 0.05700596921446083,
 '情况': 0.05674821677018335,
 '需要': 0.0565086544297889,
 '生活': 0.055387188054332896,
 '当': 0.055050211732793265,
 '认为': 0.05465365684618513,
 '各': 0.05454400105790117,
 '同时': 0.05431396661425595,
 '建设': 0.05424858314888259,
 '成': 0.05404825301210384,
 '打': 0.053862490891369214,
 '发现': 0.053776261832494884,
 '几': 0.05323643265903945,
 '网': 0.05318388051950006,
 '事': 0.05279989672074334,
 '世界': 0.05277413847144915,
 '政府': 0.05262619583385347,
 '重要': 0.05211161505568558,
 '成为': 0.0519561148946372,
 '今年': 0.05159337501282414,
 '技术': 0.05146085545892957,
 '喜欢': 0.050930809109226684,
 '还有': 0.050549395824420154,
 '产品': 0.05028994917776643,
 '无': 0.05008764335671192,
 '知道': 0.04968333444041934,
 '主要': 0.04941643117891839,
 '出现': 0.04923332454780172,
 '至': 0.048940567439380335,
 '一定': 0.048936339899908546,
 '要求': 0.04785254430017289,
 '由于': 0.04758552950810798,
 '所以': 0.047312311492295527,
 '心': 0.046806924019185,
 '长': 0.04673778569149185,
 '方面': 0.04655692560459197,
 '跟': 0.04632710891109541,
 '怎么': 0.046252479030872325,
 '希望': 0.04591123268202702,
 '生产': 0.04580455635309442,
 '外': 0.04561017451305989,
 '谁': 0.04539925959466397,
 '见': 0.0450946908684219,
 '找': 0.04475931315163228,
 '一起': 0.044740363577718524,
 '影响': 0.044694551070829515,
 '像': 0.04467395509335264,
 '带': 0.04466567527672384,
 '国际': 0.044598910956749144,
 '价格': 0.044367931158799924,
 '啦': 0.04412293037566789,
 '比赛': 0.04409319951390523,
 '投资': 0.044078907668781385,
 '如': 0.043997161076382164,
 '那么': 0.043779065714059276,
 '研究': 0.04364523965927267,
 '岁': 0.04363253048596112,
 '美': 0.043422003269049415,
 '则': 0.043347702669538954,
 '水': 0.0433006261495918,
 '起来': 0.04280492059162835,
 '快': 0.042791765296060984,
 '非常': 0.04278812196430514,
 '一直': 0.04255743958119314,
 '应该': 0.0424956516487625,
 '买': 0.04237843833702583,
 '开': 0.04227965943421703,
 '觉得': 0.04227097067218707,
 '部门': 0.042247883845448544,
 '为了': 0.04198765648484713,
 '发生': 0.04194771261001381,
 '作为': 0.04187874954463545,
 '提高': 0.041802823785478796,
 '这么': 0.0415812975305695,
 '部': 0.04099420595289365,
 '场': 0.040669115602884,
 '股': 0.04066283802542715,
 '其中': 0.04061189511259625,
 '服务': 0.04049305664121339,
 '不过': 0.04040443233070366,
 '死': 0.04021745399572401,
 '虽然': 0.04011637012792682,
 '以及': 0.0399248721496174,
 '有关': 0.03984544114416504,
 '报': 0.03981807366816237,
 '结果': 0.039686998700619966,
 '对于': 0.03964235460916286,
 '教育': 0.03958310532480698,
 '号': 0.039109116360939195,
 '笑': 0.039046977903878975,
 '组织': 0.038949935691280316,
 '只有': 0.03891871244435237,
 '城市': 0.038744390172891906,
 '人员': 0.03827459157164125,
 '而且': 0.03824378789207294,
 '作': 0.038182738185756085,
 '条': 0.038077166540504546,
 '必须': 0.03804677711731664,
 '发': 0.03794063719728686,
 '其他': 0.03766072203665791,
 '叫': 0.03760135059977961,
 '最后': 0.03759339475288421,
 '同': 0.03736824641013602,
 '提供': 0.03735689153652963,
 '只是': 0.037191284581995304,
 '不同': 0.03699900057875897,
 '项目': 0.03679280712090377,
 '因此': 0.036757446621151046,
 '学生': 0.03657417003869882,
 '支持': 0.03651893054366606,
 '使用': 0.03637384521289931,
 '之后': 0.03628961308221768,
 '应': 0.0360190824218986,
 '参加': 0.035961346766624956,
 '钱': 0.03594926428886325,
 '请': 0.03590398287989783,
 '自': 0.03589100284664525,
 '问': 0.03579779516105493,
 '继续': 0.03570686588555681,
 '老': 0.0356790204214229,
 '文化': 0.03566696449855737,
 '包括': 0.03555095146812803,
 '组': 0.035548439374949434,
 '孩子': 0.035486354027681584,
 '得到': 0.03524074248193741,
 '比较': 0.03492170664825671,
 '人民': 0.034904923953871216,
 '关系': 0.03479690925817116,
 '省': 0.034712921432534384,
 '获得': 0.03469918724023031,
 '听': 0.03462756868523398,
 '图': 0.034401937043375325,
 '总': 0.034218798546383246,
 '回': 0.03367932520853661,
 '哦': 0.03352759053176649,
 '出来': 0.032852899662573445,
 '张': 0.03270359210331414,
 '增加': 0.03264837916317756,
 '能力': 0.0324307458560482,
 '选择': 0.03242665640203654,
 '增长': 0.03234712979895794,
 '进入': 0.032276063585802144,
 '例': 0.03197231275036241,
 '一样': 0.03187563699533103,
 '所有': 0.03177933300884617,
 '系统': 0.031659480140429255,
 '女': 0.03158180706910399,
 '根据': 0.031534820835803834,
 '地方': 0.03147630446658251,
 '电': 0.03141725168845837,
 '每': 0.031358953069385714,
 '米': 0.031222508701835804,
 '其实': 0.031012942772165798,
 '规定': 0.030988066145424768,
 '款': 0.030952721578609746,
 '东西': 0.03094708662964044,
 '路': 0.03093503070677491,
 '正在': 0.03093487137739783,
 '此': 0.030933533010630385,
 '这里': 0.03087235584081187,
 '项': 0.030861107186790197,
 '未': 0.030809638487014936,
 '放': 0.030723515647725325,
 '方式': 0.030691394845306502,
 '作用': 0.03061537879950284,
 '解决': 0.030293522835847866,
 '受': 0.030208706497450288,
 '住': 0.0301390901816259,
 '头': 0.03011639636735083,
 '感觉': 0.029991317495365776,
 '转': 0.029938457319030706,
 '领导': 0.029913559448372734,
 '日本': 0.02986499054326028,
 '实现': 0.02981343155683801,
 '安全': 0.029682367211254078,
 '学习': 0.029585112559485986,
 '能够': 0.02952444524367412,
 '称': 0.029512840754043642,
 '达到': 0.02946807451006411,
 '别': 0.02946100028572187,
 '完成': 0.029437440781831345,
 '双': 0.02939722604705699,
 '以上': 0.029364149268375706,
 '全': 0.029354313334830788,
 '先': 0.02935380879180338,
 '加': 0.02934933694728674,
 '入': 0.02933464677872019,
 '件': 0.02930312080597579,
 '过程': 0.029244068027851646,
 '连': 0.029184994005810552,
 '政策': 0.02913943111494563,
 '正': 0.029138044949365057,
 '行': 0.029098451599161305,
 '环境': 0.02905756237002399,
 '信息': 0.02899892384828024,
 '设计': 0.02895690869154491,
 '存在': 0.028914096887924193,
 '开发': 0.028898424188199,
 '具有': 0.028841724173876364,
 '中心': 0.028639694523742123,
 '信': 0.02860501382933159,
 '强': 0.028601747577101506,
 '事情': 0.02860149265009818,
 '低': 0.02859031303880658,
 '决定': 0.028527781569282904,
 '朋友': 0.02831658516898747,
 '均': 0.028293030976076182,
 '标准': 0.028192780932019035,
 '去年': 0.028158498561051196,
 '有些': 0.028079279994768277,
 '便': 0.02801443824927698,
 '方法': 0.02800014109317389,
 '个人': 0.027958556125756675,
 '然后': 0.027940711235524,
 '会议': 0.027814097490539758,
 '提出': 0.027786098008008013,
 '面': 0.027558490681873597,
 '昨天': 0.027550083401743142,
 '之间': 0.027525610409424042,
 '单': 0.027487466956551694,
 '合作': 0.027454437976683538,
 '学校': 0.0274054123273568,
 '方': 0.027321721916557233,
 '成功': 0.02725197282625195,
 '水平': 0.027236358547298358,
 '代表': 0.027217260265966003,
 '达': 0.027148690213051094,
 '以后': 0.027136947637960485,
 '坚持': 0.027091990198728457,
 '介绍': 0.027089286910297373,
 '单位': 0.02698846859146198,
 '处': 0.026984049856737698,
 '随': 0.026948423808023175,
 '声': 0.026885945448291863,
 '片': 0.026873236274980318,
 '系': 0.026832262070175222,
 '队': 0.026825421528919365,
 '表现': 0.02677143011400704,
 '机构': 0.026738247115741038,
 '告诉': 0.026685333829613612,
 '资金': 0.026586268133926068,
 '过去': 0.026322912606554706,
 '写': 0.026255293218923025,
 '越': 0.02620708546039862,
 '不断': 0.02611571537362392,
 '基金': 0.026094253706531585,
 '改革': 0.02606260027028553,
 '国内': 0.02605367782516919,
 '拿': 0.026040336645328566,
 '基本': 0.025986568291544155,
 '力': 0.025905708632677334,
 '站': 0.02589848570091649,
 '建立': 0.025811752099014748,
 '曾': 0.0257783407286416,
 '原因': 0.025587814659532353,
 '进': 0.025570277806095356,
 '分析': 0.02550688064695623,
 '卡': 0.025493916546641363,
 '如何': 0.025423184925177433,
 '直接': 0.02529839815705035,
 '门': 0.025169043946780382,
 '基础': 0.025148347060698018,
 '度': 0.02508560315200491,
 '任何': 0.025044506794677394,
 '少': 0.025015009616001116,
 '送': 0.024888528645497777,
 '一般': 0.024885405789707063,
 '国': 0.02488191116536983,
 '加强': 0.02485147394336879,
 '非': 0.02479625038127374,
 '经过': 0.024766737269659757,
 '工程': 0.024738057981785806,
 '治疗': 0.02466979596566658,
 '完': 0.024641159165626526,
 '形成': 0.024618454729392985,
 '即': 0.024617716503279187,
 '级': 0.02458786879997334,
 '小时': 0.024585399194628644,
 '机会': 0.02450223988175267,
 '准备': 0.02446872760277404,
 '接受': 0.024370899365248472,
 '明显': 0.024330504057180093,
 '努力': 0.024295170112323548,
 '花': 0.024231294965053187,
 '您': 0.024220338414889492,
 '消息': 0.024218994737142806,
 '甚至': 0.02413760398035239,
 '制度': 0.024134544856312504,
 '行业': 0.024125872027220253,
 '别人': 0.024087468336365346,
 '那些': 0.02400837192260485,
 '完全': 0.023992646113087303,
 '调查': 0.02393543093377878,
 '地区': 0.023930173064335224,
 '群众': 0.02385008880843685,
 '或者': 0.02382583356626642,
 '电话': 0.023741723588107222,
 '业务': 0.023724866540012424,
 '间': 0.023709432834352853,
 '睡': 0.023709087620702517,
 '经': 0.02370830690675484,
 '学': 0.023680732302561965,
 '经营': 0.02365920159273956,
 '条件': 0.023609729821157003,
 '女人': 0.02357953690420082,
 '可是': 0.023576185676302958,
 '一切': 0.023547819736203932,
 '为什么': 0.02348144842869269,
 '仅': 0.023480051641153642,
 '终于': 0.023475462955093812,
 '相关': 0.02347511774144348,
 '进一步': 0.0234708477141378,
 '口': 0.023344621670637788,
 '精神': 0.023208283522672592,
 '功能': 0.023190762602173304,
 '人们': 0.023118405821063188,
 '按': 0.02310963739434469,
 '历史': 0.02310545234270679,
 '左右': 0.02307925859311525,
 '男人': 0.023062502453625938,
 '接': 0.02302640903873865,
 '台': 0.023007953385893842,
 '当时': 0.022938623862948197,
 '幸福': 0.02281772473162181,
 '座': 0.02279905132862833,
 '线': 0.022772788536306723,
 '呀': 0.022751273759422028,
 '处理': 0.022684546616301978,
 '银行': 0.02267118950352365,
 '质量': 0.02266454546849952,
 '许多': 0.022606910721831363,
 '下午': 0.022579298940783834,
 '刚': 0.022528775595312567,
 '近': 0.02249663885995604,
 '生': 0.022430543723365066,
 '控制': 0.022411981850935542,
 '无法': 0.02237541575889626,
 '利用': 0.022342206205734075,
 '拉': 0.022282755104167235,
 '内容': 0.02215454275443299,
 '不错': 0.022143517161539228,
 '搞': 0.022134520362713586,
 '造成': 0.02207275898517912,
 '行为': 0.02206388964985514,
 '目标': 0.022043463623713806,
 '约': 0.022026367581553394,
 '只要': 0.022000625265196912,
 '思想': 0.021983438936389484,
 '以来': 0.021959433310243148,
 '突然': 0.02181552701686677,
 '销售': 0.021770086278524274,
 '报告': 0.021735724242867897,
 '红': 0.021693108945478906,
 '交': 0.021660026855818387,
 '球': 0.021543971337555153,
 '产业': 0.021354852677943424,
 '如此': 0.02133185082687267,
 '实施': 0.021323629431015477,
 '汽车': 0.021303962874904877,
 '原来': 0.02127887380899441,
 '重': 0.021270046961504318,
 '盘': 0.021258569935375504,
 '举行': 0.0211242712034369,
 '来自': 0.02101355321930576,
 '媒体': 0.02098219188691768,
 '全部': 0.020923107242918113,
 '积极': 0.020909941325392277,
 '调整': 0.020899802666030913,
 '产生': 0.0208192244890636,
 '是否': 0.02079027434124862,
 '明天': 0.020657637945810856,
 '健康': 0.020648094116123915,
 '资源': 0.020641142044304103,
 '穿': 0.02063127424488377,
 '喝': 0.020613344378983316,
 '严重': 0.02061062515761453,
 '块': 0.020563851363483817,
 '局': 0.020551407739134067,
 '现场': 0.02052696661269038,
 '早': 0.020489030288008234,
 '男': 0.020434518397130792,
 '保护': 0.02042540475676196,
 '变化': 0.020325908871756313,
 '数': 0.02029650729070628,
 '才能': 0.020294112039070885,
 '游戏': 0.020287765418883965,
 '医院': 0.0202542478289261,
 '分钟': 0.020247152360666917,
 '显示': 0.020224655052623577,
 '参与': 0.020189183022306895,
 '坐': 0.0201857680626582,
 '专家': 0.020175225768874906,
 '套': 0.020170546796168067,
 '关于': 0.020141394831142124,
 '军': 0.020096708251851125,
 '真正': 0.02007402505953453,
 '特别': 0.020050428378789356,
 '自然': 0.02003956211527267,
 '海': 0.020032466647013487,
 '分别': 0.020021292346701122,
 '讲': 0.020016634617911224,
 '脸': 0.019984710321724133,
 '上市': 0.019968878292621867,
 '取得': 0.019912810284828303,
 '专业': 0.01987649380881311,
 '超过': 0.01986218603075155,
 '仍': 0.019844935970193295,
 '注意': 0.019821323356510413,
 '未来': 0.01977873992499684,
 '最近': 0.01970416315456611,
 '重点': 0.019672669047697128,
 '电影': 0.019595994440468213,
 '句': 0.01958922294194242,
 '较': 0.01957573836566243,
 '不仅': 0.019490932649223323,
 '法律': 0.01947625841359449,
 '帮助': 0.01946941256135939,
 '结束': 0.019449358303764572,
 '拥有': 0.019211808824500527,
 '除了': 0.019120996390545597,
 '带来': 0.019016996795147893,
 '改变': 0.01901332159751664,
 '办法': 0.01900708119691444,
 '帮': 0.018978030140493977,
 '共': 0.018968284493596072,
 '书': 0.01896562369299888,
 '结构': 0.018955304460343495,
 '楼': 0.018921064577209545,
 '拍': 0.018864821307101196,
 '保持': 0.018862245482171778,
 '类': 0.018815413267269473,
 '某': 0.01877673871647353,
 '价值': 0.018743555718207527,
 '不少': 0.018672415151342436,
 '检查': 0.018660720375064947,
 '求': 0.01860562958745079,
 '认识': 0.01860070099871986,
 '变': 0.018569727367816,
 '农村': 0.018395288254812344,
 '包': 0.01839390208923177,
 '任务': 0.018382425063102954,
 '按照': 0.018372451044097904,
 '推荐': 0.018368032309373623,
 '选': 0.0183217896131665,
 '考虑': 0.018313674436894023,
 '靠': 0.018302393916996937,
 '快乐': 0.018295872034495234,
 '科技': 0.01827837235791289,
 '全面': 0.018273693385206048,
 '当然': 0.018141773971965133,
 '受到': 0.018118724322081257,
 '者': 0.018109663791504787,
 '另外': 0.01809521261700386,
 '期': 0.01801081584596592,
 '晚': 0.018010183839436845,
 '字': 0.01800417181094179,
 '干部': 0.01798481860260611,
 '开展': 0.017984430901121888,
 '多少': 0.017948804852407366,
 '相信': 0.017925622428042593,
 '管': 0.01788237512412453,
 '另': 0.017865491521133554,
 '指': 0.017819604660535237,
 '有效': 0.017809168586336663,
 '容易': 0.017808605622537655,
 '而是': 0.01776608061179568,
 '收入': 0.01776121575481558,
 '人士': 0.01767702611196784,
 '不到': 0.01765393397425008,
 '十分': 0.017646270231212652,
 '政治': 0.01764213828936711,
 '之前': 0.017634416125558088,
 '交易': 0.017622466422277275,
 '正常': 0.01757790730648794,
 '新闻': 0.017548744719503528,
 '地址': 0.01753528138714048,
 '购': 0.017514260531324728,
 '短': 0.01743072944990224,
 '收': 0.017377603724605374,
 '改': 0.017238976544589495,
 '克': 0.017224190778396705,
 '原': 0.017191060889923063,
 '马': 0.01716828209998022,
 '实际': 0.017127748706451708,
 '传统': 0.017062933515856592,
 '换': 0.017055280394777637,
 '首': 0.01702016420006976,
 '药': 0.017003174377494067,
 '常': 0.01700128366888608,
 '效果': 0.016982764284290443,
 '责任': 0.016979174062326963,
 '店': 0.01695848779820307,
 '卖': 0.016958328468825994,
 '有的': 0.01690493719456733,
 '科学': 0.01687277921529386,
 '共同': 0.016843175817032863,
 '气': 0.016816737762396474,
 '措施': 0.016793029551087343,
 '指出': 0.01679071396414049,
 '神': 0.016784802844250914,
 '难': 0.016728750769395055,
 '意义': 0.016712488550974684,
 '经验': 0.01671206367263581,
 '创新': 0.016683559647076646,
 '建议': 0.0166232056790397,
 '伤': 0.016621755781708294,
 '黑': 0.0165937350552596,
 '办': 0.016523826635577242,
 '白': 0.016512328365531483,
 '期间': 0.016503140371453347,
 '飞': 0.01649493490853386,
 '真是': 0.016467678963095138,
 '程度': 0.016466276864576856,
 '患者': 0.016369829481652623,
 '以前': 0.016337283800894928,
 '远': 0.016261172157465018,
 '山': 0.016250789193058803,
 '正式': 0.016209421975790256,
 '家庭': 0.01618641481374027,
 '动': 0.016183599994745234,
 '具体': 0.016171655602443658,
 '肯定': 0.016144006644541478,
 '光': 0.0161379468172333,
 '段': 0.01611118479286352,
 '血': 0.016102533207688213,
 '亲': 0.016050066043816598,
 '联系': 0.01604461697912055,
 '导致': 0.016029215139336393,
 '吨': 0.016028482224201834,
 '更加': 0.016025624917372912,
 '深': 0.016021785079385346,
 '身体': 0.016007949978475787,
 '结合': 0.016005267933961648,
 '引起': 0.01599034939328796,
 '优势': 0.015985128700699056,
 '开心': 0.01598024791078125,
 '西': 0.015946039893522713,
 '因素': 0.01594187077482252,
 '风': 0.015933383830003527,
 '老师': 0.01592055250416955,
 '油': 0.015880343080374434,
 '人生': 0.015864983728424167,
 '活': 0.0157996586838224,
 '数据': 0.0157990372992518,
 '行动': 0.015716026693794433,
 '音乐': 0.01571259580120803,
 '减少': 0.01565519473762625,
 '压力': 0.015649219885985846,
 '范围': 0.015598229174341817,
 '促进': 0.015586019233078448,
 '层': 0.015570596149377348,
 '竞争': 0.015560298160638905,
 '简单': 0.015546882627088981,
 '跑': 0.015535028521434418,
 '干': 0.015522133463849615,
 '最好': 0.015499763619307938,
 '用户': 0.015480049264384217,
 '冷': 0.01547935352610431,
 '相': 0.015471482654876684,
 '利益': 0.015428394680335697,
 '需求': 0.01541714071533479,
 '病': 0.015367865449983966,
 '风险': 0.015361970263032097,
 '运动': 0.015354593312873411,
 '还要': 0.015339775680805207,
 '空间': 0.015321819260008576,
 '装': 0.015314028053469486,

In [40]:
# Add to dataset
count_match = 0
for entry in vocabulary_data:
    simp_char = entry["simplified"]
    freq = freq_lookup.get(simp_char, None)

    if freq: count_match += 1

    entry["relative_freq_pct"] = freq

print(count_match)

7420

In [41]:
# Upsert
repsonse = client.table("vocabulary").upsert(vocabulary_data).execute()

In [43]:
# Query to validate
response = client.table("vocabulary").select("*").is_("relative_freq_pct", "null").execute()

None

In [45]:
len(response.data)

373